title: AlexP Photography
author: João Neto
email: shots@pirozhenko.me
description: >-
  Hi, my name is Alex. I'm an amateur photographer and outdoor enthusiast based
  in California, and this is a gallery of my favorite shots. Look around, enjoy
  the pictures, and leave a comment!

social:
  instagram: alex.pi.photography

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
